name: demoparty_assistant
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  carousel_slider_plus: ^6.0.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  go_router: ^14.6.1
  google_fonts: ^6.2.1
  stroke_text: ^0.0.3
  beautiful_soup_dart: ^0.3.0
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.1.1
  flutter_login: ^5.0.0
  flutter_form_bloc: ^0.31.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.3
  numberpicker: ^2.1.2
  permission_handler: ^11.3.1
  oauth2_client: ^3.3.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.2
  flutter_appauth: ^8.0.0+1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  android_intent_plus: ^5.2.0
  chewie: ^1.8.5
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3
  get_thumbnail_video: ^0.7.3
  image_picker: ^1.1.2
  hive: ^2.2.3
  get_it: ^8.0.2
  hive_flutter: ^1.1.0
  country_flags: ^3.0.0
  flag: ^7.0.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/logo/demoparty_assistant_logo.png"
  # adaptive_icon_foreground: "assets/logo_foreground.png"
  # adaptive_icon_background: "#ffffff"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/data/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
    # - family: Montserrat
    #   fonts:
    #     - asset: assets/fonts/Montserrat-Regular.ttf
    #     - asset: assets/fonts/Montserrat-Bold.ttf
    #       weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
